ftplugin and bashrc'

diff --git a/conf/bashrc b/conf/bashrc
--- a/conf/bashrc
+++ b/conf/bashrc
@@ -202,3 +202,25 @@ fi
 # Use Neovim instead of vim
 alias vi=nvim
 alias vim=nvim
+
+# Color prompt according to exit code: https://stackoverflow.com/a/16715681
+PROMPT_COMMAND=__prompt_command # Func to gen PS1 after CMDs
+
+__prompt_command() {
+    local EXIT="$?"             # This needs to be first
+
+    local RCol='\[\e[0m\]'
+
+    local Red='\[\e[0;31m\]'
+    local Gre='\[\e[0;32m\]'
+    local BYel='\[\e[1;33m\]'
+    local BBlu='\[\e[1;34m\]'
+    local Pur='\[\e[0;35m\]'
+
+    PS1="${Gre}\u@\h:"
+    if [ $EXIT != 0 ]; then
+        PS1+="${Red}\w\$ ${RCol}"      # Add red if exit code non 0
+    else
+        PS1+="${BBlu}\w\$ ${RCol}"
+    fi
+}
